AWSTemplateFormatVersion: '2010-09-09'
Description: Adds a parameter to parameter store
Parameters:

  DevPass:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mydb/Dev/Password
    NoEcho: True
  DevLogin:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mydb/Dev/Login

  VPC:
    Type: String
    Default: vpc-0e77ef725616198b6
  CIDR1:
    Type: String
    Default: "10.2.202.0/24"
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
  CIDR2:
    Type: String
    Default: "10.2.203.0/24"
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
  CIDR3:
    Type: String
    Default: "10.2.204.0/24"
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    
   
Resources:
          
    DevDB:
        Type: AWS::RDS::DBCluster
        Properties:
            Engine: aurora
            EngineMode: serverless
            DatabaseName: "DevDB"
            MasterUsername: !Ref DevLogin
            MasterUserPassword: !Ref DevPass
            DBClusterIdentifier: !Join [ "-", ["DevDBCluster",!Ref "AWS::StackName"]]
            DBSubnetGroupName: !Ref DBSubnetGroup
            BackupRetentionPeriod: 1
            DeletionProtection: false
            StorageEncrypted: true
            Tags:
            - Key: CostCenter
              Value: "1520"
#        VpcSecurityGroupIds:
#            - !Ref VpcSecurityGroupId
        
    DBSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: "MySQL DB Subnet"
            DBSubnetGroupName: !Join [ '-',["mydbsubnet",!Ref "AWS::StackName"]]
            SubnetIds: 
            - !Ref DBSubnet01
            - !Ref DBSubnet02
            - !Ref DBSubnet03
            
    DBSubnet01:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-2a"
            CidrBlock: !Ref CIDR1
            VpcId: !Ref VPC
            Tags:
            - Key: Name
              Value: !Join [ '-' , [ "db2a",!Ref "AWS::StackName" ] ]            
    DBSubnet02:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-2b"
            CidrBlock: !Ref CIDR2
            VpcId: !Ref VPC
            Tags:
            - Key: Name
              Value: !Join [ '-' , [ "db2b",!Ref "AWS::StackName" ] ]
            
    DBSubnet03:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: "us-east-2c"
            CidrBlock: !Ref CIDR3
            VpcId: !Ref VPC
            Tags:
            - Key: Name
              Value: !Join [ '-' , [ "db2c",!Ref "AWS::StackName" ] ]                